#!/bin/sh

TARGET=${ESP32_TARGET-esp32c3}

if [ -z "$IDF_PATH" ]
then
    echo "Must set IDF_PATH" 1>&2
    exit 1
fi

set -e

rm -rf build sdkconfig

if [ -d sdkconfig.${TARGET} ]
then
    cp sdkconfig.${TARGET} sdkconfig.defaults
fi

idf.py set-target ${TARGET}

idf.py fullclean
idf.py build

if [ -n "$ESPPORT" ]
then
    idf.py flash monitor
fi
